## test spreadsheet number formats represent date-time values

test_that("'isDateFormat( format )' should be true", {
  expect_true( colspec_is_date_format(  "yyyy-mm-dd" ) )
  expect_true( colspec_is_date_format(  "m-d-yy" ) )
  expect_true( colspec_is_date_format(  "mm-dd-yy" ) )
  expect_true( colspec_is_date_format(  "mm-dd" ) )
  expect_true( colspec_is_date_format(  "mmm-yy" ) )
  expect_true( colspec_is_date_format(  "m/d/yy" ) )
  expect_true( colspec_is_date_format(  "m/d/yy h:mm" ) )
  expect_true( colspec_is_date_format(  "d-mmm-yy" ) )
  expect_true( colspec_is_date_format(  "d-mmm" ) )
  expect_true( colspec_is_date_format(  "h:mm AM/PM" ) )
  expect_true( colspec_is_date_format(  "h:mm:ss AM/PM" ) )
  expect_true( colspec_is_date_format(  "h:mm" ) )
  expect_true( colspec_is_date_format(  "h:mm:ss" ) )
  expect_true( colspec_is_date_format(  "mm:ss" ) )
  expect_true( colspec_is_date_format(  "mmss.0" ) )
  expect_true( colspec_is_date_format(  "[$-411]ge.m.d" ) )
  expect_true( colspec_is_date_format(  "[$-411]ggge\"年\"m\"月\"d\"日\"" ) )
  expect_true( colspec_is_date_format(  "yyyy\"年\"m\"月\"" ) )
  expect_true( colspec_is_date_format(  "yyyy\"年\"m\"月\"d\"日\"" ) )
  expect_true( colspec_is_date_format(  "yyyy\"年\" mm\"月\" dd\"日\"" ) )
  expect_true( colspec_is_date_format(  "m\"月\"d\"日\"" ) )
  expect_true( colspec_is_date_format(  "h\"時\"mm\"分\"" ) )
  expect_true( colspec_is_date_format(  "h\"時\"mm\"分\"ss\"秒\"" ) )
  expect_true( colspec_is_date_format(  "hh\"時\"mm\"分\"" ) )
  expect_true( colspec_is_date_format(  "hh\"時\"mm\"分\"ss\"秒\"" ) )
  expect_true( colspec_is_date_format(  "[$-411]ggge\"年\"m\"月\"d\"日\"" ) )
  expect_true( colspec_is_date_format(  "yyyy\"년\" mm\"월\" dd\"일\"" ) )
  expect_true( colspec_is_date_format(  "h\"시\" mm\"분\"" ) )
  expect_true( colspec_is_date_format(  "h\"시\" mm\"분\" ss\"초\"" ) )
  expect_true( colspec_is_date_format(  "d/m/bb" ) )
  expect_true( colspec_is_date_format(  "上午/下午h\"时\"mm\"分\"" ) )
  expect_true( colspec_is_date_format(  "上午/下午hh\"時\"mm\"分\"" ) )
  expect_true( colspec_is_date_format(  "上午/下午h\"时\"mm\"分\"ss\"秒\"" ) )
  expect_true( colspec_is_date_format(  "上午/下午hh\"時\"mm\"分\"ss\"秒\"" ) )
  expect_true( colspec_is_date_format(  "[$-404]e\"年\"m\"月\"d\"日\"" ) )
  expect_true( colspec_is_date_format(  "[$-404]e/m/d" ) )
  expect_true( colspec_is_date_format(  "[$-404]e\"年\"m\"月\"d\"日\"" ) )

  # cases that should pass but fail with current colSpec isDataFormat C++ code
  # expect_true( colspec_is_date_format(  "ว/ด/ปปปป" ) )
  # expect_true( colspec_is_date_format(  "ว-ดดด-ปป" ) )
  # expect_true( colspec_is_date_format(  "ว-ดดด" ) )
  # expect_true( colspec_is_date_format(  "ดดด-ปป" ) )
  # expect_true( colspec_is_date_format(  "ช:นน" ) )
  # expect_true( colspec_is_date_format(  "ช:นน:ทท" ) )
  # expect_true( colspec_is_date_format(  "ว/ด/ปปปป ช:นน" ) )
  # expect_true( colspec_is_date_format(  "นน:ทท" ) )
  # expect_true( colspec_is_date_format(  "นน:ทท.0" ) )
})

test_that("isDateFormat( format )' should be false", {
  expect_false( colspec_is_date_format(  "General" ) )
  expect_false( colspec_is_date_format(  "0" ) )
  expect_false( colspec_is_date_format(  "0.00" ) )
  expect_false( colspec_is_date_format(  "#,##0" ) )
  expect_false( colspec_is_date_format(  "#,##0.00" ) )
  expect_false( colspec_is_date_format(  "0%" ) )
  expect_false( colspec_is_date_format(  "0.00%" ) )
  expect_false( colspec_is_date_format(  "0.00E+00" ) )
  expect_false( colspec_is_date_format(  "# ?/?" ) )
  expect_false( colspec_is_date_format(  "# ??/??" ) )
  expect_false( colspec_is_date_format(  "#,##0;(#,##0)" ) )
  expect_false( colspec_is_date_format(  "#,##0.00;(#,##0.00)" ) )
  expect_false( colspec_is_date_format(  "##0.0E+0" ) )
  expect_false( colspec_is_date_format(  "@" ) )
  expect_false( colspec_is_date_format(  "t0" ) )
  expect_false( colspec_is_date_format(  "t0.00" ) )
  expect_false( colspec_is_date_format(  "t#,##0" ) )
  expect_false( colspec_is_date_format(  "t#,##0.00" ) )
  expect_false( colspec_is_date_format(  "t0%" ) )
  expect_false( colspec_is_date_format(  "t0.00%" ) )
  expect_false( colspec_is_date_format(  "t# ?/?" ) )
  expect_false( colspec_is_date_format(  "t# ??/??" ) )
  expect_false( colspec_is_date_format(  "[ช]:นน:ทท" ) )

  # cases that should pass but fail with current colSpec isDataFormat C++ code
  # expect_false( colspec_is_date_format(  "#,##0.00;[Red](#,##0.00)" ) )
  # expect_false( colspec_is_date_format(  "#,##0;[Red](#,##0)" ) )
  # expect_false( colspec_is_date_format(  "[h]:mm:ss" ) )
})
